grid_map_visualization:
  grid_map_topic: /terrain_map
  grid_map_visualizations:
    - name: z_points
      type: point_cloud
      params:
       layer: z
    - name: elevation_grid
      type: occupancy_grid
      params:
       layer: z
       data_min: 0.08
       data_max: -0.16
    - name: surface_normals
      type: vectors
      params:
        layer_prefix: normal_vectors_
        position_layer: z
        scale: 0.06
        line_width: 0.005
        color: 15600153 # red