terrain_map_publisher:
  update_rate: 5
  map_data_source: internal
  terrain_type: slope     # slope, rough_terrain, or step
  resolution: 0.1
  obstacle_x: 3.0
  obstacle_y: 0.0
  obstacle_radius: 1.0
  obstacle_height: 1.0
  step1_x: 1.0
  step1_height: 0.0
  step2_x: 2.0
  step2_height: 0.0

map_frame: map